# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileTestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobileTestApp
  pod 'Alamofire', '~> 4.7.1'
  pod 'AlamofireObjectMapper', '~> 5.2'
  target 'MobileTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MobileTestAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
